version: '3.4'

services:
  db:
    build:
      context: ./db
    env_file:
      - './db/.env'
    networks:
      - backend
    ports:
      - '5432:5432'
    volumes:
      - './db/data/pgdata:/var/lib/postgresql/data/pgdata'
    restart: always
  rest:
    build:
      context: ./rest
    depends_on:
       - db
    env_file:
      - './rest/.env'
    networks:
      - backend
    ports:
      - '5002:5002'
    restart: on-failure
    volumes:
      - './rest:/rest'

networks:
  backend: